name: voz_app
description: Voice word tracker app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Audio & Speech
  record: ^5.1.0
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.0
  
  # Background service
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.2.2
  
  # Storage
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.2.3
  
  # UI
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
